openapi: 3.2.0
info:
  title: RCSB Search Metadata Service API
  description: Provides programmatic access to RCSB search API.
  contact:
    email: info@rcsb.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.6.0
servers:
- url: /
  description: Default URL
tags:
- name: Metadata Service
paths:
  /rcsbsearch/v2/metadata/unreleased/schema:
    get:
      tags:
      - Metadata Service
      summary: Get RCSB PDB unreleased entry schema
      operationId: getUnreleasedEntryMetadata
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JsonNode'
  /rcsbsearch/v2/metadata/schema:
    get:
      tags:
      - Metadata Service
      summary: Get RCSB PDB structure data schema as JSON Schema
      operationId: getMetadata
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JsonNode'
  /rcsbsearch/v2/metadata/chemical/schema:
    get:
      tags:
      - Metadata Service
      summary: Get RCSB PDB chemical data schema as JSON Schema
      operationId: getChemicalMetadata
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JsonNode'
components:
  schemas:
    JsonNode:
      type: object
