openapi: 3.2.0
info:
  title: RCSB Search Suggest Service API
  description: Provides programmatic access to RCSB search API.
  contact:
    email: info@rcsb.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.6.0
servers:
- url: /
  description: Default URL
tags:
- name: Suggest Service
paths:
  /rcsbsearch/v2/suggest:
    get:
      tags:
      - Suggest Service
      summary: Provides auto-complete/search-as-you-type functionality
      operationId: getSuggestions
      parameters:
      - name: json
        in: query
        description: Suggest query. Must be URL-encoded.
        required: true
        schema:
          $ref: schema/suggest/request/json-schema-rcsb_suggest.json
      responses:
        '200':
          description: "OK.\n Request has succeeded."
          content:
            application/json:
              schema:
                $ref: schema/suggest/response/json-schema-rcsb_suggest_results.json
        '500':
          description: "Internal Server Error.\n The server encountered unexpected error"
          content:
            application/json:
              schema:
                type: object
        '204':
          description: "No Content.\n The server successfully processed the request and did not return any results"
          content:
            application/json:
              schema:
                type: object
